### ISSUE TITLE
undefined method `capitalize' 

### ISSUE THREAD

**Issue by krisrmgua** [ondreian/ProfanityFE#16]
followed directions https://gswiki.play.net/Lich_(software)#Fedora

and https://gswiki.play.net/Profanity

And when i lauch the game i get: 

[ksimmons@localhost ProfanityFE-onedreian]$ ./profanity.rb 
Traceback (most recent call last):
	1: from ./profanity.rb:50:in `<main>'
./profanity.rb:60:in `<module:Profanity>': undefined method `capitalize' for nil:NilClass (NoMethodError)

If i use the other one by matt-lowe (git clone https://github.com/matt-lowe/ProfanityFE.git) it works but not yours? It says its recommend to use yours what am i doing wrong?

**Comment by mrhoribu** [comment]
Ondreian's fork requires you to specify a character profile (See the templates folder for example on this repo)  to use when launching. So it would be 
```
./profanity.rb --char=Tysong
```
or something similar. You'll also be required to have the associated XML file for the character specified in your home .profanity hidden directory. For my example that would be tysong.xml.

**Comment by krisrmgua** [comment]
worked thanks!
